production: &ldap_defaults
  hostname: <%= ENV['HOSTNAME'] || 'localhost' %>
  basedn: ou=users,dc=test
  auth: false
  port: <%= ENV['PORT'] || '3897' %>
  username_ldap_attribut: uid


test:
  <<: *ldap_defaults

development:
  <<: *ldap_defaults